export * from './auth.controller';
export * from './board.controller'
export * from './class.controller'
export * from './subject.controller'
export * from './chapter.controller'
export * from './topic.controller'
export * from './assignClass.controller'
export * from './student.controller'
export * from './googleAuth.controller'
